-- Supabase setup for Utentes MenteMovimento.
-- Run this file in Supabase Dashboard > SQL Editor before enabling the
-- SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY environment variables.

create table if not exists public.utentes (
    id bigint generated by default as identity primary key,
    nome text not null,
    data_nascimento text,
    telefone text,
    email text,
    morada text,
    numero_utente text,
    nif text,
    contacto_emergencia text,
    estado text not null default 'Ativo',
    observacoes text,
    created_at text not null,
    updated_at text not null
);

create index if not exists idx_utentes_nome on public.utentes (nome);
create index if not exists idx_utentes_estado on public.utentes (estado);

create table if not exists public.utilizadores (
    id bigint generated by default as identity primary key,
    nome text not null,
    email text not null unique,
    password_hash text not null,
    perfil text not null check (perfil in ('Administrador', 'Utilizador')),
    ativo integer not null default 1 check (ativo in (0, 1)),
    tema text not null default 'escuro',
    idioma text not null default 'pt',
    created_at text not null,
    updated_at text not null
);

create index if not exists idx_utilizadores_email on public.utilizadores (email);
create index if not exists idx_utilizadores_perfil on public.utilizadores (perfil);

create table if not exists public.sessoes (
    token text primary key,
    utilizador_id bigint not null references public.utilizadores(id) on delete cascade,
    created_at text not null,
    expires_at text not null
);

create index if not exists idx_sessoes_utilizador on public.sessoes (utilizador_id);
create index if not exists idx_sessoes_expires on public.sessoes (expires_at);

create table if not exists public.utente_abas (
    id bigint generated by default as identity primary key,
    utente_id bigint not null references public.utentes(id) on delete cascade,
    tab_key text not null,
    conteudo text not null default '',
    created_at text not null,
    updated_at text not null,
    unique (utente_id, tab_key)
);

create index if not exists idx_utente_abas_utente on public.utente_abas (utente_id);

create table if not exists public.historico (
    id bigint generated by default as identity primary key,
    utilizador_id bigint references public.utilizadores(id) on delete set null,
    utilizador_nome text not null,
    acao text not null,
    alvo_tipo text not null,
    alvo_id bigint,
    detalhes text,
    created_at text not null
);

create index if not exists idx_historico_created on public.historico (created_at);
create index if not exists idx_historico_utilizador on public.historico (utilizador_id);

create table if not exists public.utente_anexos (
    id bigint generated by default as identity primary key,
    utente_id bigint not null references public.utentes(id) on delete cascade,
    tab_key text not null,
    original_name text not null,
    stored_name text not null,
    size_bytes bigint not null,
    uploaded_by bigint references public.utilizadores(id) on delete set null,
    uploaded_by_name text,
    created_at text not null
);

create index if not exists idx_utente_anexos_utente on public.utente_anexos (utente_id);

-- Keep direct browser/public keys away from clinical data. The app backend uses
-- the service role key on the server side, which bypasses RLS.
alter table public.utentes enable row level security;
alter table public.utilizadores enable row level security;
alter table public.sessoes enable row level security;
alter table public.utente_abas enable row level security;
alter table public.historico enable row level security;
alter table public.utente_anexos enable row level security;

-- Private bucket for scanned PDF documents.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('documentos-utentes', 'documentos-utentes', false, 31457280, array['application/pdf'])
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;
