-- Full setup for Aplicativos MenteMovimento.
-- Run this once in Supabase Dashboard > SQL Editor.

do $$
begin
  if not exists (select 1 from pg_type where typname = 'member_role') then
    create type public.member_role as enum ('admin', 'manager', 'member');
  end if;

  if not exists (select 1 from pg_type where typname = 'device_status') then
    create type public.device_status as enum ('active', 'maintenance', 'retired');
  end if;
end $$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique,
  full_name text,
  role public.member_role not null default 'admin',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.devices (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  serial_number text not null unique,
  model text not null,
  location text,
  status public.device_status not null default 'active',
  notes text,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists devices_status_idx on public.devices(status);
create index if not exists devices_serial_number_idx on public.devices(serial_number);

create table if not exists public.device_history (
  id uuid primary key default gen_random_uuid(),
  device_id uuid,
  device_name text,
  serial_number text,
  action text not null,
  summary text,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now()
);

create table if not exists public.device_attachments (
  id uuid primary key default gen_random_uuid(),
  device_id uuid not null references public.devices(id) on delete cascade,
  file_name text not null,
  file_path text not null unique,
  file_type text,
  file_size bigint,
  uploaded_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now()
);

create index if not exists device_history_device_id_idx on public.device_history(device_id);
create index if not exists device_attachments_device_id_idx on public.device_attachments(device_id);

create table if not exists public.utentes (
  id bigint generated by default as identity primary key,
  nome text not null,
  data_nascimento text,
  telefone text,
  email text,
  morada text,
  numero_utente text,
  nif text,
  contacto_emergencia text,
  estado text not null default 'Ativo',
  observacoes text,
  created_at text not null,
  updated_at text not null
);

create index if not exists idx_utentes_nome on public.utentes(nome);
create index if not exists idx_utentes_estado on public.utentes(estado);

create table if not exists public.utilizadores (
  id bigint generated by default as identity primary key,
  nome text not null,
  email text not null unique,
  password_hash text not null,
  perfil text not null check (perfil in ('Administrador', 'Utilizador')),
  ativo integer not null default 1 check (ativo in (0, 1)),
  tema text not null default 'escuro',
  idioma text not null default 'pt',
  created_at text not null,
  updated_at text not null
);

create index if not exists idx_utilizadores_email on public.utilizadores(email);
create index if not exists idx_utilizadores_perfil on public.utilizadores(perfil);

create table if not exists public.sessoes (
  token text primary key,
  utilizador_id bigint not null references public.utilizadores(id) on delete cascade,
  created_at text not null,
  expires_at text not null
);

create index if not exists idx_sessoes_utilizador on public.sessoes(utilizador_id);
create index if not exists idx_sessoes_expires on public.sessoes(expires_at);

create table if not exists public.utente_abas (
  id bigint generated by default as identity primary key,
  utente_id bigint not null references public.utentes(id) on delete cascade,
  tab_key text not null,
  conteudo text not null default '',
  created_at text not null,
  updated_at text not null,
  unique (utente_id, tab_key)
);

create index if not exists idx_utente_abas_utente on public.utente_abas(utente_id);

create table if not exists public.historico (
  id bigint generated by default as identity primary key,
  utilizador_id bigint references public.utilizadores(id) on delete set null,
  utilizador_nome text not null,
  acao text not null,
  alvo_tipo text not null,
  alvo_id bigint,
  detalhes text,
  created_at text not null
);

create index if not exists idx_historico_created on public.historico(created_at);
create index if not exists idx_historico_utilizador on public.historico(utilizador_id);

create table if not exists public.utente_anexos (
  id bigint generated by default as identity primary key,
  utente_id bigint not null references public.utentes(id) on delete cascade,
  tab_key text not null,
  original_name text not null,
  stored_name text not null,
  size_bytes bigint not null,
  uploaded_by bigint references public.utilizadores(id) on delete set null,
  uploaded_by_name text,
  created_at text not null
);

create index if not exists idx_utente_anexos_utente on public.utente_anexos(utente_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists set_devices_updated_at on public.devices;
create trigger set_devices_updated_at
before update on public.devices
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name, role)
  values (new.id, new.email, nullif(new.raw_user_meta_data->>'full_name', ''), 'admin')
  on conflict (id) do update
  set email = excluded.email,
      full_name = coalesce(public.profiles.full_name, excluded.full_name),
      role = 'admin';

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

insert into public.profiles (id, email, full_name, role)
select id, email, nullif(raw_user_meta_data->>'full_name', ''), 'admin'
from auth.users
on conflict (id) do update
set email = excluded.email,
    role = 'admin';

alter table public.profiles enable row level security;
alter table public.devices enable row level security;
alter table public.device_history enable row level security;
alter table public.device_attachments enable row level security;
alter table public.utentes enable row level security;
alter table public.utilizadores enable row level security;
alter table public.sessoes enable row level security;
alter table public.utente_abas enable row level security;
alter table public.historico enable row level security;
alter table public.utente_anexos enable row level security;

drop policy if exists "Authenticated members can read profiles" on public.profiles;
drop policy if exists "Authenticated members can update profiles" on public.profiles;
drop policy if exists "Authenticated members can read devices" on public.devices;
drop policy if exists "Authenticated members can create devices" on public.devices;
drop policy if exists "Authenticated members can update devices" on public.devices;
drop policy if exists "Authenticated members can delete devices" on public.devices;
drop policy if exists "Authenticated members can read device history" on public.device_history;
drop policy if exists "Authenticated members can create device history" on public.device_history;
drop policy if exists "Authenticated members can read device attachments" on public.device_attachments;
drop policy if exists "Authenticated members can create device attachments" on public.device_attachments;
drop policy if exists "Authenticated members can delete device attachments" on public.device_attachments;

create policy "Authenticated members can read profiles"
on public.profiles for select to authenticated using (true);

create policy "Authenticated members can update profiles"
on public.profiles for update to authenticated using (true) with check (true);

create policy "Authenticated members can read devices"
on public.devices for select to authenticated using (true);

create policy "Authenticated members can create devices"
on public.devices for insert to authenticated with check (true);

create policy "Authenticated members can update devices"
on public.devices for update to authenticated using (true) with check (true);

create policy "Authenticated members can delete devices"
on public.devices for delete to authenticated using (true);

create policy "Authenticated members can read device history"
on public.device_history for select to authenticated using (true);

create policy "Authenticated members can create device history"
on public.device_history for insert to authenticated with check (true);

create policy "Authenticated members can read device attachments"
on public.device_attachments for select to authenticated using (true);

create policy "Authenticated members can create device attachments"
on public.device_attachments for insert to authenticated with check (true);

create policy "Authenticated members can delete device attachments"
on public.device_attachments for delete to authenticated using (true);

insert into storage.buckets (id, name, public)
values ('device-attachments', 'device-attachments', false)
on conflict (id) do nothing;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('documentos-utentes', 'documentos-utentes', false, 31457280, array['application/pdf'])
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Authenticated members can read device attachment files" on storage.objects;
drop policy if exists "Authenticated members can create device attachment files" on storage.objects;
drop policy if exists "Authenticated members can delete device attachment files" on storage.objects;

create policy "Authenticated members can read device attachment files"
on storage.objects for select to authenticated using (bucket_id = 'device-attachments');

create policy "Authenticated members can create device attachment files"
on storage.objects for insert to authenticated with check (bucket_id = 'device-attachments');

create policy "Authenticated members can delete device attachment files"
on storage.objects for delete to authenticated using (bucket_id = 'device-attachments');

notify pgrst, 'reload schema';
