-- Exemplo inicial de organização para uma única Supabase.
-- Executar primeiro num projeto de teste, nunca diretamente na produção.

create schema if not exists socios;
create schema if not exists utentes;
create schema if not exists dispositivos;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  nome text,
  role text not null default 'viewer',
  can_socios boolean not null default false,
  can_utentes boolean not null default false,
  can_dispositivos boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists socios.members (
  id bigint generated by default as identity primary key,
  nome text not null,
  email text,
  nif text,
  categoria text,
  estado text not null default 'Ativo',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists utentes.utentes (
  id bigint generated by default as identity primary key,
  nome text not null,
  data_nascimento date,
  telefone text,
  email text,
  estado text not null default 'Ativo',
  observacoes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists dispositivos.devices (
  id bigint generated by default as identity primary key,
  nome text not null,
  numero_serie text,
  modelo text,
  local text,
  estado text not null default 'Ativo',
  notas text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table socios.members enable row level security;
alter table utentes.utentes enable row level security;
alter table dispositivos.devices enable row level security;
